name: docker build

on:
  push:
  workflow_dispatch: # manual

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      -
        name: pwd and ls
        run: |
          pwd
          ls -la
      -
        name: Checkout
        uses: actions/checkout@v5
      -
        name: pwd and ls
        run: |
          pwd
          ls -la
      -
        # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          version: v0.29.0
    
      - name: Check buildx command
        run: docker buildx ls

      - name: check docker version
        run: docker version

      - name: check docker buildx version
        run: docker buildx version